### ISSUE TITLE
Dead

### ISSUE THREAD

**Issue by FreQRiDeR** [freechessclub/freechessclub#2]
No longer works/connects in modern MacOS. (Mojave and above with Safari.) Please update! It’s been 3 years.

**Comment by freechessclub-dev** [comment]
Hi @FreQRiDeR, Sorry for the delay. Version 1.4.2 was just released and it should work on newer macOS. Please try it out.
If for any reason the desktop app doesn't work, you could always use the web interface at https://www.freechess.club/play to play. Thanks!
