### ISSUE TITLE
Can't Move Pieces in Monterey

### ISSUE THREAD

**Issue by FreQRiDeR** [freechessclub/freechessclub#3]
12.2.1. Intel Mac. Connects to FICS no problem but can not move pieces when joining a game? Do I need Java installed/updated? Also Console on left is covering action buttons. Same in window mode/full screen. Installing latest Java did not help. Works fine in Mojave.

![Screen Shot 2022-03-05 at 1 53 26 PM](https://user-images.githubusercontent.com/31628763/156896482-e741efc6-7e38-48fe-847e-3ef70ba2566d.png)

**Comment by freechessclub-dev** [comment]
I regularly used the app on Monterey and now run it on Ventura.
Do you still see the issue?
Could you please try the latest 2.0 release? Thanks!

**Comment by FreQRiDeR** [comment]
I will try it when I get a chance. Thanks for the update!

**Comment by FreQRiDeR** [comment]
Ok, It works fine now! One thing I noticed is the captured piece images are missing or broken? Other than that, seems to work fine. I'm on Monterey 12.4, intel mac. JRE 17 or 18 I believe?
 
![ECCAE202-D1BA-435C-A6F1-85594B2F6E43](https://user-images.githubusercontent.com/31628763/209034277-305a5cdf-95e2-44d3-be8f-0d06db7287b3.png)

**Comment by freechessclub-dev** [comment]
Closing this issue. Captured image pieces should display fine with the latest release.
